trigger:
- ci

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'instala dependências'

- script: npm run cy:run-junit
  displayName: 'Executa os testes'

- task: PublishTestResults@2
  displayName: 'Gerar Relatório'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
